[workspace]
resolver = "2"
members = [
    "srtb-integration",
    "srtb-integration-cli",
    "srtb-integration-gui",
]

[workspace.dependencies]
srtb-integration = { path = "srtb-integration" }

rfd = "0.14.1"
strum = { version = "0.26.2", features = ["derive"] }
