name: Rust CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install -y libgtk-3-dev
    - run: cargo test --verbose

  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt -- --check
  
  clippy-desktop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo clippy --all -- -D warnings
  
  clippy-wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - run: cargo clippy --target wasm32-unknown-unknown --all -- -D warnings
