name: Build Release

on:
  workflow_dispatch:
  create:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install -y libgtk-3-dev
    - name: Build release
      run: cargo build --release
    - name: Upload CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: srtb-integration-linux-cli
        path: target/release/srtb-integration-cli
    - name: Upload GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: srtb-integration-linux-gui
        path: target/release/srtb-integration-gui

  publish-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload CLI artifact
      uses: actions/upload-artifact@v3
      with:
        name: srtb-integration-windows-cli.exe
        path: target/release/srtb-integration-cli.exe
    - name: Upload GUI artifact
      uses: actions/upload-artifact@v3
      with:
        name: srtb-integration-windows-gui.exe
        path: target/release/srtb-integration-gui.exe
