[package]
name = "srtb-integration-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.12.1"
rfd = { workspace = true }
srtb-integration = { workspace = true }
strum = { workspace = true }
